name: App CI/ CD Workflow

on:
  push:
    branches:
      - main

jobs:
    pytest:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Set Up Python
              uses: actions/setup-python@v2
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: Lint with flake8
              run: |
                pip install flake8
                # stop the build if there are Python syntax errors or undefined names
                flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
                flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

            - name: Test with pytest
              run: |
                pip install pytest
                pytest .

    package_image:
        runs-on: ubuntu-latest
        needs: pytest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

            - name: Build and push docker image
              run: |
                docker buildx create --use
                docker buildx build \
                  --platform linux/amd64,linux/arm64 \
                  --file Dockerfile \
                  --tag higherwil1995/whisky-map:latest \
                  --push .

    image_build_test:
      runs-on: ubuntu-latest
      needs: package_image
      steps:
          - uses: actions/checkout@v2
          - name: Build the stack
            run: docker-compose up -d

    deploy_to_ec2:
      runs-on: ubuntu-latest
      # needs: image_build_test
      steps:
        - name: Set permissons for private key
          run: |
            echo "${{ secrets.EC2_PRIVATE_KEY }}" > key.pem
            chmod 600 key.pem

        - name: Set docker-compose.yml
          run: |
            echo "${{ secrets.DOCKER_COMPOSE_FILE }}" > docker-compose.yml

        - name: pull new code
          run: |
            scp -o StrictHostKeyChecking=no -i key.pem docker-compose.yml ubuntu@43.198.111.149:/home/ubuntu/
            ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@43.198.111.149 "sudo cat /home/ubuntu/docker-compose.yml"
        

        # - name: Set permissons for private key
        #   run: |
        #     echo "${{ secrets.EC2_PRIVATE_KEY }}" > key.pem
        #     chmod 600 key.pem

        # - name: Pull Repository
        #   run: |
        #     ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@43.198.111.149 'sudo docker pull higherwil1995/whisky-map:latest'

