name: FastAPI Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
          DOCKER_BUILDKIT: 1
        run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build \
            --file Dockerfile \
            --tag higherwil1995/whisky-map:latest \
            --push .

  deploy_to_ec2:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - name: SSH to Ubuntu server
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add EC2 host to known hosts
        run: ssh-keyscan -H 18.162.120.66 >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          sudo docker rm -f whisky-map-app || true
          sudo docker pull higherwil1995/whisky-map:latest
          sudo docker run --name whisky-map-app -p 8000:8000 -d higherwil1995/whisky-map:latest
